"""empty message

Revision ID: 75abd9c65628
Revises: 
Create Date: 2022-06-01 17:20:19.001814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75abd9c65628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
